server:
  port: 8010

spring:
  application:
    name: dbapi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/svenmoo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: bsy
    password: bsy

mybatis:
  type-aliases-package: com.bsy.dbapi.entity
  mapper-locations: mapper/*.xml


