server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/svenmoo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: bsy
    password: bsy

mybatis:
  type-aliases-package: com.bsy.spring.api.entities
  mapper-locations: mappers/*.xml

logging:
  file:
    path: logs
